#
# Makefile for the accelerometer drivers.
#

# Each configuration option enables a list of files.



obj-$(CONFIG_HUAWEI_FEATURE_SENSORS_ACCELEROMETER_ST_LIS3XH)	+= gs_st_lis3xh.o
obj-$(CONFIG_HUAWEI_FEATURE_SENSORS_ACCELEROMETER_KX023)	+= gs_rohm_kx023.o
obj-$(CONFIG_HUAWEI_FEATURE_SENSORS_AKM8963)	+= akm8963.o
obj-$(CONFIG_HUAWEI_FEATURE_PROXIMITY_EVERLIGHT_APS_AVAGO_9930)	+= aps_avago_9930.o


